"""
Shielding demo — model.py generated by OpenMC Studio

Fixed-source run: 6 cells, 1 source, 2 tallies, seed 12345.
Run it inside your OpenMC environment (OpenMC 0.14 or newer):
    python model.py
OPENMC_CROSS_SECTIONS must point at a cross_sections.xml.
"""
import openmc

# ── Materials ──────────────────────────────────────────────
# PNNL #248
mat_polyethylene = openmc.Material(name="Polyethylene")
mat_polyethylene.set_density("g/cm3", 0.93)
mat_polyethylene.add_element("H", 0.143716, "wo")
mat_polyethylene.add_element("C", 0.856284, "wo")
mat_polyethylene.add_s_alpha_beta("c_H_in_CH2")

# PNNL #171
mat_lead = openmc.Material(name="Lead")
mat_lead.set_density("g/cm3", 11.35)
mat_lead.add_element("Pb", 1.0, "wo")

# Ideal gas, 4 atm, 20 °C
mat_he_3_detector_gas_4_atm = openmc.Material(name="He-3 detector gas (4 atm)")
mat_he_3_detector_gas_4_atm.set_density("g/cm3", 5.02e-4)
mat_he_3_detector_gas_4_atm.add_nuclide("He3", 1.0, "ao")

# PNNL #97
mat_concrete_ordinary_nist = openmc.Material(name="Concrete, ordinary (NIST)")
mat_concrete_ordinary_nist.set_density("g/cm3", 2.3)
mat_concrete_ordinary_nist.add_element("H", 0.0221, "wo")
mat_concrete_ordinary_nist.add_element("C", 0.002484, "wo")
mat_concrete_ordinary_nist.add_element("O", 0.57493, "wo")
mat_concrete_ordinary_nist.add_element("Na", 0.015208, "wo")
mat_concrete_ordinary_nist.add_element("Mg", 0.001266, "wo")
mat_concrete_ordinary_nist.add_element("Al", 0.019953, "wo")
mat_concrete_ordinary_nist.add_element("Si", 0.304627, "wo")
mat_concrete_ordinary_nist.add_element("K", 0.010045, "wo")
mat_concrete_ordinary_nist.add_element("Ca", 0.042951, "wo")
mat_concrete_ordinary_nist.add_element("Fe", 0.006435, "wo")

materials = openmc.Materials([mat_polyethylene, mat_lead, mat_he_3_detector_gas_4_atm, mat_concrete_ordinary_nist])

# ── Geometry ───────────────────────────────────────────────
# Every surface is created once and shared, so faces that touch (or sit on the world
# boundary) are one surface and particles are never lost between them.
# Parts listed first win where shapes overlap (same order as the Explorer).
xplane_m100 = openmc.XPlane(-100.0, boundary_type="vacuum")
xplane_100 = openmc.XPlane(100.0, boundary_type="vacuum")
yplane_m100 = openmc.YPlane(-100.0, boundary_type="vacuum")
yplane_100 = openmc.YPlane(100.0, boundary_type="vacuum")
zplane_m100 = openmc.ZPlane(-100.0, boundary_type="vacuum")
zplane_100 = openmc.ZPlane(100.0, boundary_type="vacuum")
world = +xplane_m100 & -xplane_100 & +yplane_m100 & -yplane_100 & +zplane_m100 & -zplane_100

zcyl_r2p5 = openmc.ZCylinder(x0=60.0, y0=0.0, r=2.5)
zplane_m10 = openmc.ZPlane(-10.0)
zplane_10 = openmc.ZPlane(10.0)
shape_he_3_detector = -zcyl_r2p5 & +zplane_m10 & -zplane_10
sphere_r5 = openmc.Sphere(r=5.0)
shape_source_cavity = -sphere_r5
sphere_r25 = openmc.Sphere(r=25.0)
shape_moderator = -sphere_r25
sphere_r32 = openmc.Sphere(r=32.0)
shape_lead_shield = -sphere_r32
zplane_m70 = openmc.ZPlane(-70.0)
shape_floor_slab = +xplane_m100 & -xplane_100 & +yplane_m100 & -yplane_100 & +zplane_m100 & -zplane_m70

cell_he_3_detector = openmc.Cell(name="He-3 detector", fill=mat_he_3_detector_gas_4_atm, region=shape_he_3_detector & world)
cell_source_cavity = openmc.Cell(name="Source cavity", fill=None, region=shape_source_cavity & world & ~(shape_he_3_detector))
cell_moderator = openmc.Cell(name="Moderator", fill=mat_polyethylene, region=shape_moderator & world & ~(shape_he_3_detector | shape_source_cavity))
cell_lead_shield = openmc.Cell(name="Lead shield", fill=mat_lead, region=shape_lead_shield & world & ~(shape_he_3_detector | shape_source_cavity | shape_moderator))
cell_floor_slab = openmc.Cell(name="Floor slab", fill=mat_concrete_ordinary_nist, region=shape_floor_slab & world & ~(shape_he_3_detector | shape_source_cavity | shape_moderator | shape_lead_shield))
cell_world = openmc.Cell(name="World", fill=None, region=world & ~(shape_he_3_detector | shape_source_cavity | shape_moderator | shape_lead_shield | shape_floor_slab))
geometry = openmc.Geometry([cell_he_3_detector, cell_source_cavity, cell_moderator, cell_lead_shield, cell_floor_slab, cell_world])

# ── Sources ────────────────────────────────────────────────
src_d_t_generator = openmc.IndependentSource()
src_d_t_generator.particle = "neutron"
src_d_t_generator.space = openmc.stats.Point((0.0, 0.0, 0.0))
src_d_t_generator.angle = openmc.stats.Isotropic()
src_d_t_generator.energy = openmc.stats.Discrete([1.41e7], [1.0])  # eV
src_d_t_generator.strength = 1.0

# ── Tallies ────────────────────────────────────────────────
tally_detector_spectrum = openmc.Tally(name="Detector spectrum")
tally_detector_spectrum.filters = [openmc.CellFilter([cell_he_3_detector]), openmc.EnergyFilter([0.0, 0.5, 100000.0, 2e7])]
tally_detector_spectrum.scores = ["flux", "(n,p)"]

mesh_flux_map_xz = openmc.RegularMesh(name="Flux map (XZ)")
mesh_flux_map_xz.dimension = [100, 1, 100]
mesh_flux_map_xz.lower_left = [-100.0, -5.0, -100.0]
mesh_flux_map_xz.upper_right = [100.0, 5.0, 100.0]
tally_flux_map_xz = openmc.Tally(name="Flux map (XZ)")
tally_flux_map_xz.filters = [openmc.MeshFilter(mesh_flux_map_xz)]
tally_flux_map_xz.scores = ["flux"]

tallies = openmc.Tallies([tally_detector_spectrum, tally_flux_map_xz])

# ── Settings ───────────────────────────────────────────────
settings = openmc.Settings()
settings.run_mode = "fixed source"
settings.particles = 10000
settings.batches = 10
settings.seed = 12345  # same seed + same model = the same particle histories
settings.source = [src_d_t_generator]
settings.max_tracks = 50

model = openmc.Model(geometry=geometry, materials=materials, settings=settings, tallies=tallies)

if __name__ == "__main__":
    statepoint = model.run(tracks=True)
    print(f"Finished: {statepoint}")
    print("Particle tracks written to tracks.h5 (open with openmc.Tracks)")
