// Exercise the real application with the same DOM harness as the model tests.
const fs = require('fs'), vm = require('vm'), path = require('path'), assert = require('assert');
const harness = fs.readFileSync(path.join(__dirname, 'test_frontend_model.js'), 'utf8').split('// Set up mock test state')[0];
const checks = `
let pixels;
const canvas = {getContext: () => ({createImageData: (w,h) => ({data:new Uint8ClampedArray(w*h*4)}), putImageData: img => {pixels=img.data;}})};
sandbox.document.createElement = () => canvas;
vm.runInContext("view.plane='xy'; view.slice=3;", sandbox);
const tally = {mesh_type:'cylindrical',dims:[2,2,1],r_grid:[1,2,4],phi_grid:[0,Math.PI,2*Math.PI],z_grid:[-1,1],origin:[10,20,3],scores:['flux'],values:{flux:[1,2,3,4]}};
const ctx = new Proxy({}, {get:()=>()=>{},set:()=>true});
const render = (x,y) => sandbox.drawMesh3D(ctx,{pos:[x,y,13],f:[0,0,-1],r:[1,0,0],u:[0,1,0],focal:1},tally,1,1);
render(11.5,20.5); assert.equal(pixels[3],204,'inside annular bin must render');
const first = Array.from(pixels);
render(11.5,19.5); assert.notDeepEqual(Array.from(pixels),first,'angular bins must use different values');
render(10,20); assert.equal(pixels[3],0,'annular hole must be transparent');
render(15,20); assert.equal(pixels[3],0,'outside radius must be transparent');
vm.runInContext("V3.depth={w:1,h:1,buf:new Uint8Array([0,0,0,255]),tmax:100};",sandbox);
render(11.5,20.5); assert.equal(pixels[3],0,'geometry depth must occlude mesh');
vm.runInContext("V3.depth=null;",sandbox);
const regular={mesh_type:'regular',dims:[1,1,1],lower:[0,0,2],upper:[2,2,4],scores:['flux'],values:{flux:[1]}};
sandbox.drawMesh3D(ctx,{pos:[1,1,13],f:[0,0,-1],r:[1,0,0],u:[0,1,0],focal:1},regular,1,1);
assert.equal(pixels[3],204,'regular mesh overlay must still render');
const modelTally={id:'cyl',meshGeom:'cylindrical',kind:'mesh',scores:['flux'],ox:0,oy:0,oz:0,rmax:20,zmin:-25,zmax:25,nr:10,nphi:8,nz:15,ebins:''};
const context={cells:[],surfaces:[],materials:[],tallyScores:[modelTally],groups:[]};
const deck='Title\\n1 0 -1\\n\\n1 SO 100\\n\\nFMESH4:N GEOM=CYL ORIGIN=0 0 -25 AXS=0 0 1 VEC=1 0 0\\n     IMESH=20 IINTS=10 JMESH=50 JINTS=15 KMESH=1 KINTS=8\\n';
const refs=sandbox.annotateMcnp(deck,context,true).refs;
assert.equal(JSON.stringify(refs.map(r=>r.key)),JSON.stringify(['ox','oy','nr','nz','nphi']));
const angular=refs.find(r=>r.key==='nphi');
assert.equal(sandbox.applyEdit(angular,12),null);
assert.equal(modelTally.nphi,12); assert.equal(modelTally.nz,15);
sandbox.__t=modelTally;
vm.runInContext('S.tallies=[__t];',sandbox);
assert.match(sandbox.mcnpTally(modelTally),/KINTS=12/);
assert.match(sandbox.buildScript([],false).text,/phi_grid=np.linspace\\(0.0, 6.28318530718, 13\\)/);
modelTally.meshGeom='regular';
assert.equal(JSON.stringify(sandbox.annotateMcnp(deck.replace('GEOM=CYL','GEOM=XYZ'),context,true).refs.map(r=>r.key)),JSON.stringify(['lx','ly','lz','ux','nx','uy','ny','uz','nz']));
console.log('Cylindrical rendering, occlusion and edit round trips PASSED');
`;
vm.runInNewContext(harness+checks,{require,console,URLSearchParams,__dirname,process,assert});
