"""Unit tests for studio/openmc_studio/depletion_script.py.

Verifies script generation, AST structure, safe quoting, deterministic output,
real OpenMC depletion API signatures, stub script execution, and thorough
settings validation.
"""
import ast
import inspect
import math
from pathlib import Path
import runpy
import sys
import tempfile
import types
import unittest
from unittest.mock import MagicMock, patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "studio"))

from openmc_studio import depletion_script  # noqa: E402
from openmc_studio.depletion_script import INTEGRATORS, ScriptError, build_script  # noqa: E402

import openmc  # noqa: E402
import openmc.deplete  # noqa: E402

VALID_SETTINGS = {
    "model_path": "/path/to/model.py",
    "chain_file": "/path/to/chain.xml",
    "integrator": "CECMIntegrator",
    "time_steps_days": [10.0, 20.0, 30.0],
    "power_w": 1000.0,
}


class TestDepletionScriptAST(unittest.TestCase):
    """Test 1: Output parsing, header comment, and AST statements for each integrator."""

    def test_integrators_ast_structure(self):
        for name in INTEGRATORS:
            with self.subTest(integrator=name):
                settings = dict(VALID_SETTINGS, integrator=name)
                script = build_script(settings)

                # Header comment is the first line
                lines = script.splitlines()
                self.assertEqual(
                    lines[0],
                    "# Generated by Studio's depletion_script.py; edit the settings, not this file.",
                )
                self.assertTrue(script.endswith("\n"))
                self.assertFalse(script.endswith("\n\n"))

                # Script parses with ast.parse
                tree = ast.parse(script)

                # AST has exactly the 8 statements listed:
                # 3 imports, run_path call, model assignment, operator call, integrator call, integrate call
                self.assertEqual(len(tree.body), 8)

                # Statement 0: import runpy
                self.assertIsInstance(tree.body[0], ast.Import)
                self.assertEqual(len(tree.body[0].names), 1)
                self.assertEqual(tree.body[0].names[0].name, "runpy")

                # Statement 1: import openmc
                self.assertIsInstance(tree.body[1], ast.Import)
                self.assertEqual(len(tree.body[1].names), 1)
                self.assertEqual(tree.body[1].names[0].name, "openmc")

                # Statement 2: import openmc.deplete
                self.assertIsInstance(tree.body[2], ast.Import)
                self.assertEqual(len(tree.body[2].names), 1)
                self.assertEqual(tree.body[2].names[0].name, "openmc.deplete")

                # Statement 3: namespace = runpy.run_path(...)
                self.assertIsInstance(tree.body[3], ast.Assign)
                self.assertEqual(len(tree.body[3].targets), 1)
                self.assertIsInstance(tree.body[3].targets[0], ast.Name)
                self.assertEqual(tree.body[3].targets[0].id, "namespace")
                self.assertIsInstance(tree.body[3].value, ast.Call)
                self.assertIsInstance(tree.body[3].value.func, ast.Attribute)
                self.assertEqual(tree.body[3].value.func.value.id, "runpy")
                self.assertEqual(tree.body[3].value.func.attr, "run_path")

                # Statement 4: model = namespace["model"]
                self.assertIsInstance(tree.body[4], ast.Assign)
                self.assertEqual(len(tree.body[4].targets), 1)
                self.assertIsInstance(tree.body[4].targets[0], ast.Name)
                self.assertEqual(tree.body[4].targets[0].id, "model")
                self.assertIsInstance(tree.body[4].value, ast.Subscript)
                self.assertIsInstance(tree.body[4].value.value, ast.Name)
                self.assertEqual(tree.body[4].value.value.id, "namespace")
                self.assertIsInstance(tree.body[4].value.slice, ast.Constant)
                self.assertEqual(tree.body[4].value.slice.value, "model")

                # Statement 5: operator = openmc.deplete.CoupledOperator(model, chain_file=...)
                self.assertIsInstance(tree.body[5], ast.Assign)
                self.assertEqual(len(tree.body[5].targets), 1)
                self.assertIsInstance(tree.body[5].targets[0], ast.Name)
                self.assertEqual(tree.body[5].targets[0].id, "operator")
                self.assertIsInstance(tree.body[5].value, ast.Call)
                self.assertEqual(tree.body[5].value.func.attr, "CoupledOperator")

                # Statement 6: integrator = openmc.deplete.<integrator>(operator, ..., power=..., timestep_units="d")
                self.assertIsInstance(tree.body[6], ast.Assign)
                self.assertEqual(len(tree.body[6].targets), 1)
                self.assertIsInstance(tree.body[6].targets[0], ast.Name)
                self.assertEqual(tree.body[6].targets[0].id, "integrator")
                self.assertIsInstance(tree.body[6].value, ast.Call)
                self.assertEqual(tree.body[6].value.func.attr, name)

                # Statement 7: integrator.integrate()
                self.assertIsInstance(tree.body[7], ast.Expr)
                self.assertIsInstance(tree.body[7].value, ast.Call)
                self.assertIsInstance(tree.body[7].value.func, ast.Attribute)
                self.assertEqual(tree.body[7].value.func.value.id, "integrator")
                self.assertEqual(tree.body[7].value.func.attr, "integrate")

                # Exactly 4 calls and no other calls in the AST
                all_calls = [n for n in ast.walk(tree) if isinstance(n, ast.Call)]
                self.assertEqual(len(all_calls), 4)


class TestDepletionScriptStubRun(unittest.TestCase):
    """Test 2: Stub run for each integrator."""

    def test_stub_execution(self):
        for chosen_name in INTEGRATORS:
            with self.subTest(integrator=chosen_name):
                stub_openmc = types.ModuleType("openmc")
                stub_deplete = types.ModuleType("openmc.deplete")
                stub_openmc.deplete = stub_deplete

                mock_operator_cls = MagicMock(name="CoupledOperator")
                mock_operator_inst = MagicMock(name="operator_instance")
                mock_operator_cls.return_value = mock_operator_inst
                stub_deplete.CoupledOperator = mock_operator_cls

                mock_integrator_classes = {}
                mock_integrator_instances = {}
                for name in INTEGRATORS:
                    cls_mock = MagicMock(name=name)
                    inst_mock = MagicMock(name=f"{name}_instance")
                    cls_mock.return_value = inst_mock
                    setattr(stub_deplete, name, cls_mock)
                    mock_integrator_classes[name] = cls_mock
                    mock_integrator_instances[name] = inst_mock

                with tempfile.TemporaryDirectory(prefix="studio-depl-") as tmp:
                    tmp_path = Path(tmp)
                    model_file = tmp_path / "model.py"
                    model_file.write_text("model = 'MODEL'\n", encoding="utf-8")

                    settings = {
                        "model_path": str(model_file),
                        "chain_file": "/data/chain_endfb71.xml",
                        "integrator": chosen_name,
                        "time_steps_days": [10, 20, 30],  # ints converted to floats
                        "power_w": 5000,                  # int converted to float
                    }

                    script_text = build_script(settings)
                    script_file = tmp_path / "run_depletion.py"
                    script_file.write_text(script_text, encoding="utf-8")

                    with patch.dict(sys.modules, {"openmc": stub_openmc, "openmc.deplete": stub_deplete}):
                        runpy.run_path(str(script_file))

                # CoupledOperator called once with "MODEL" and keyword chain_file
                mock_operator_cls.assert_called_once_with("MODEL", chain_file="/data/chain_endfb71.xml")

                # The chosen integrator called once with operator, timesteps as floats, power, and timestep_units="d"
                mock_integrator_classes[chosen_name].assert_called_once_with(
                    mock_operator_inst,
                    [10.0, 20.0, 30.0],
                    power=5000.0,
                    timestep_units="d",
                )

                # No other integrator called
                for name, cls_mock in mock_integrator_classes.items():
                    if name != chosen_name:
                        cls_mock.assert_not_called()

                # integrate() called exactly once on the chosen integrator instance
                mock_integrator_instances[chosen_name].integrate.assert_called_once_with()


class TestDepletionScriptQuoting(unittest.TestCase):
    """Test 3: Quoting safe against quotes, backslashes, newlines, and unicode."""

    def test_quoting_safety(self):
        dangerous_strings = [
            'x"); import os; os.system("echo hi"); ("',
            'quotes"and\'more`triple"""and\'\'\'',
            "path\\with\\backslash\nand_newline.py",
            "/tmp/модель/🚀/ñ/file.py",
        ]

        for s in dangerous_strings:
            with self.subTest(dangerous_string=s):
                # Test as model_path
                settings_model = dict(VALID_SETTINGS, model_path=s)
                script_m = build_script(settings_model)
                tree_m = ast.parse(script_m)
                self.assertEqual(len(tree_m.body), 8)
                run_path_call = tree_m.body[3].value
                self.assertEqual(len(run_path_call.args), 1)
                self.assertIsInstance(run_path_call.args[0], ast.Constant)
                self.assertEqual(run_path_call.args[0].value, s)
                calls_m = [n for n in ast.walk(tree_m) if isinstance(n, ast.Call)]
                self.assertEqual(len(calls_m), 4)

                # Test as chain_file
                settings_chain = dict(VALID_SETTINGS, chain_file=s)
                script_c = build_script(settings_chain)
                tree_c = ast.parse(script_c)
                self.assertEqual(len(tree_c.body), 8)
                op_call = tree_c.body[5].value
                chain_kws = [kw for kw in op_call.keywords if kw.arg == "chain_file"]
                self.assertEqual(len(chain_kws), 1)
                self.assertIsInstance(chain_kws[0].value, ast.Constant)
                self.assertEqual(chain_kws[0].value.value, s)
                calls_c = [n for n in ast.walk(tree_c) if isinstance(n, ast.Call)]
                self.assertEqual(len(calls_c), 4)


class TestDepletionScriptDeterminism(unittest.TestCase):
    """Test 4: Determinism with repeated calls."""

    def test_determinism(self):
        script1 = build_script(VALID_SETTINGS)
        script2 = build_script(VALID_SETTINGS)
        self.assertEqual(script1, script2)


class TestRealOpenMCPackage(unittest.TestCase):
    """Test 5: Check against the real installed openmc.deplete package."""

    def test_real_package_signatures(self):
        self.assertTrue(hasattr(openmc.deplete, "CoupledOperator"))
        op_sig = inspect.signature(openmc.deplete.CoupledOperator)
        self.assertIn("model", op_sig.parameters)
        self.assertIn("chain_file", op_sig.parameters)

        for name in INTEGRATORS:
            with self.subTest(integrator=name):
                self.assertTrue(hasattr(openmc.deplete, name))
                cls = getattr(openmc.deplete, name)
                sig = inspect.signature(cls)
                self.assertIn("operator", sig.parameters)
                self.assertIn("timesteps", sig.parameters)
                self.assertIn("power", sig.parameters)
                self.assertIn("timestep_units", sig.parameters)
                self.assertTrue(hasattr(cls, "integrate"))


class TestDepletionScriptValidation(unittest.TestCase):
    """Test 6 & 7: Validation and bad-input rules for each ScriptError."""

    def test_settings_not_dict(self):
        bad_settings = [None, [], (), "settings", 123, True]
        for bad in bad_settings:
            with self.subTest(bad=bad):
                with self.assertRaises(ScriptError) as ctx:
                    build_script(bad)
                self.assertIn("settings", str(ctx.exception))

    def test_missing_keys(self):
        for key in ("model_path", "chain_file", "integrator", "time_steps_days", "power_w"):
            with self.subTest(missing_key=key):
                settings = dict(VALID_SETTINGS)
                del settings[key]
                with self.assertRaises(ScriptError) as ctx:
                    build_script(settings)
                self.assertIn(key, str(ctx.exception))

    def test_extra_keys(self):
        settings = dict(VALID_SETTINGS, unexpected_key="bad")
        with self.assertRaises(ScriptError) as ctx:
            build_script(settings)
        self.assertIn("unexpected_key", str(ctx.exception))

    def test_unknown_integrator(self):
        bad_integrators = ["UnknownIntegrator", "MyIntegrator", "", 123, None, True]
        for bad in bad_integrators:
            with self.subTest(bad=bad):
                settings = dict(VALID_SETTINGS, integrator=bad)
                with self.assertRaises(ScriptError) as ctx:
                    build_script(settings)
                self.assertIn("integrator", str(ctx.exception))

    def test_bad_model_path(self):
        bad_paths = ["", None, 123, [], True, False]
        for bad in bad_paths:
            with self.subTest(bad=bad):
                settings = dict(VALID_SETTINGS, model_path=bad)
                with self.assertRaises(ScriptError) as ctx:
                    build_script(settings)
                self.assertIn("model_path", str(ctx.exception))

    def test_bad_chain_file(self):
        bad_chains = ["", None, 123, [], True, False]
        for bad in bad_chains:
            with self.subTest(bad=bad):
                settings = dict(VALID_SETTINGS, chain_file=bad)
                with self.assertRaises(ScriptError) as ctx:
                    build_script(settings)
                self.assertIn("chain_file", str(ctx.exception))

    def test_bad_time_steps_days(self):
        bad_timesteps = [
            [],                      # empty
            [0],                     # 0
            [1.0, 0.0],              # step of 0
            [-1.0],                  # negative
            [10.0, -5.0],            # negative in list
            [float("nan")],          # nan
            [10.0, float("nan")],    # nan in list
            [float("inf")],          # inf
            [float("-inf")],         # -inf
            [True],                  # bool
            [False],                 # bool false
            [10.0, True],            # bool in list
            ["10"],                  # string
            [1.0, "20.0"],           # string in list
            [None],                  # None
            (10.0, 20.0),            # tuple, not list
            "10.0",                  # string, not list
            10.0,                    # float, not list
            None,                    # None, not list
            True,                    # bool, not list
        ]
        for bad in bad_timesteps:
            with self.subTest(bad=bad):
                settings = dict(VALID_SETTINGS, time_steps_days=bad)
                with self.assertRaises(ScriptError) as ctx:
                    build_script(settings)
                self.assertIn("time_steps_days", str(ctx.exception))

    def test_bad_power_w(self):
        bad_powers = [
            0,
            0.0,
            -10,
            -0.5,
            float("nan"),
            float("inf"),
            float("-inf"),
            True,
            False,
            "1000",
            None,
            [1000.0],
        ]
        for bad in bad_powers:
            with self.subTest(bad=bad):
                settings = dict(VALID_SETTINGS, power_w=bad)
                with self.assertRaises(ScriptError) as ctx:
                    build_script(settings)
                self.assertIn("power_w", str(ctx.exception))


class TestAddedByTheDispatcher(unittest.TestCase):
    """Added by the dispatcher after a mutation check showed a gap in the brief's test list."""

    def test_integers_are_written_as_floats(self):
        """10 must appear as 10.0 and a power of 1000000 as 1000000.0 (the brief says floats via float())."""
        text = build_script(dict(VALID_SETTINGS, time_steps_days=[10, 20, 30], power_w=1000000))
        self.assertIn("[10.0, 20.0, 30.0]", text)
        self.assertIn("power=1000000.0,", text)


class TestOptionsAddedForStudio(unittest.TestCase):
    """The options Studio's depletion run needs: power per gram of heavy metal, a reduced chain, and the model's prepare hook."""

    SETTINGS = {
        "model_path": "/path/to/model.py",
        "chain_file": "/path/to/chain.xml",
        "integrator": "CECMIntegrator",
        "time_steps_days": [1, 4],
        "power_density": 38,
        "reduce_chain_level": 6,
        "prepare": True,
    }

    def test_stub_run_calls_prepare_first_and_passes_the_options(self):
        import builtins
        events = []
        builtins._depl_events = events
        try:
            stub_openmc = types.ModuleType("openmc")
            stub_deplete = types.ModuleType("openmc.deplete")
            stub_openmc.deplete = stub_deplete
            operator_inst = MagicMock(name="operator_instance")
            operator_cls = MagicMock(name="CoupledOperator", side_effect=lambda *a, **k: events.append("operator") or operator_inst)
            integrator_cls = MagicMock(name="CECMIntegrator")
            stub_deplete.CoupledOperator = operator_cls
            for name in INTEGRATORS:
                setattr(stub_deplete, name, integrator_cls if name == "CECMIntegrator" else MagicMock(name=name))
            with tempfile.TemporaryDirectory(prefix="studio-depl-") as tmp:
                model_file = Path(tmp) / "model.py"
                model_file.write_text("import builtins\nmodel = 'MODEL'\n"
                                      "def prepare_depletion(m):\n    builtins._depl_events.append('prepare:' + m)\n", encoding="utf-8")
                script_file = Path(tmp) / "run.py"
                script_file.write_text(build_script(dict(self.SETTINGS, model_path=str(model_file))), encoding="utf-8")
                with patch.dict(sys.modules, {"openmc": stub_openmc, "openmc.deplete": stub_deplete}):
                    runpy.run_path(str(script_file))
        finally:
            del builtins._depl_events
        self.assertEqual(events, ["prepare:MODEL", "operator"], "the volumes are set before the operator reads the model")
        operator_cls.assert_called_once_with("MODEL", chain_file="/path/to/chain.xml", reduce_chain_level=6)
        integrator_cls.assert_called_once_with(operator_inst, [1.0, 4.0], power_density=38.0, timestep_units="d")

    def test_without_the_options_the_script_has_no_prepare_and_no_reduction(self):
        text = build_script(dict(VALID_SETTINGS))
        self.assertNotIn("prepare_depletion", text)
        self.assertNotIn("reduce_chain_level", text)
        self.assertIn("power=1000.0", text)
        self.assertNotIn("power_density", text)

    def test_both_powers_is_an_error_and_neither_names_both(self):
        with self.assertRaises(ScriptError) as ctx:
            build_script(dict(self.SETTINGS, power_w=10.0))
        self.assertIn("not both", str(ctx.exception))
        settings = dict(self.SETTINGS)
        del settings["power_density"]
        with self.assertRaises(ScriptError) as ctx:
            build_script(settings)
        self.assertIn("power_density", str(ctx.exception))

    def test_bad_option_values_are_refused(self):
        for key, bad in (("power_density", 0), ("power_density", -1.0), ("power_density", True), ("power_density", float("nan")),
                         ("reduce_chain_level", 0), ("reduce_chain_level", True), ("reduce_chain_level", 2.5), ("reduce_chain_level", "6"),
                         ("prepare", "yes"), ("prepare", 1)):
            with self.subTest(key=key, bad=bad):
                with self.assertRaises(ScriptError):
                    build_script(dict(self.SETTINGS, **{key: bad}))


class TestResumeAndRates(unittest.TestCase):
    BASE = {"model_path": "/path/to/model.py", "chain_file": "/path/to/chain.xml", "integrator": "PredictorIntegrator", "time_steps_days": [1, 4, 10],
            "power_density": 38, "reduce_chain_level": 3, "prepare": True}

    def test_write_rates_only_changes_the_integrate_call(self):
        plain, rates = build_script(dict(self.BASE)), build_script(dict(self.BASE, write_rates=True))
        self.assertIn("integrator.integrate()\n", plain)
        self.assertEqual(rates, plain.replace("integrator.integrate()\n", "integrator.integrate(write_rates=True)\n"))

    def test_the_options_off_give_the_script_byte_for_byte_as_before(self):
        self.assertEqual(build_script(dict(self.BASE, write_rates=False, resume=False)), build_script(dict(self.BASE)))

    def test_resume_reads_the_earlier_results_continues_the_step_list_and_does_not_measure_volumes(self):
        text = build_script(dict(self.BASE, write_rates=True, resume=True))
        self.assertIn('namespace["prepare_depletion"](model, measure_volumes=False)\n', text)
        self.assertIn('previous = openmc.deplete.Results("depletion_results.h5")\n', text)
        self.assertIn("previous[-1].transfer_volumes(model)", text)
        self.assertLess(text.index("previous = "), text.index("previous[-1].transfer_volumes(model)"))
        self.assertLess(text.index("previous[-1].transfer_volumes(model)"), text.index("CoupledOperator("), "the volumes are on the model before the operator checks them")
        self.assertIn("prev_results=previous", text)
        self.assertIn("continue_timesteps=True", text)
        self.assertIn("integrator.integrate(write_rates=True)\n", text)
        self.assertLess(text.index("measure_volumes=False"), text.index("previous = "), "the model is prepared, then the results are read, then the operator is built")
        self.assertLess(text.index("previous = "), text.index("CoupledOperator("))
        self.assertIn("[1.0, 4.0, 10.0]", text, "the whole original step list: OpenMC skips the steps already done")

    def test_resume_without_write_rates_is_refused_with_the_reason(self):
        with self.assertRaises(ScriptError) as ctx:
            build_script(dict(self.BASE, resume=True))
        self.assertIn("burn wrongly", str(ctx.exception))

    def test_bad_values_are_refused(self):
        for key, bad in (("write_rates", "yes"), ("write_rates", 1), ("resume", "yes"), ("resume", 1), ("resume", None)):
            with self.subTest(key=key, bad=bad):
                with self.assertRaises(ScriptError):
                    build_script({**self.BASE, "write_rates": True, key: bad})

    def test_stub_run_of_a_resume_gives_openmc_what_it_needs_in_the_right_order(self):
        import builtins
        events = []
        builtins._depl_events = events
        try:
            stub_openmc = types.ModuleType("openmc")
            stub_deplete = types.ModuleType("openmc.deplete")
            stub_openmc.deplete = stub_deplete
            prev = MagicMock(name="PREV")
            prev.__getitem__.return_value.transfer_volumes.side_effect = lambda m: events.append("volumes:" + m)
            stub_deplete.Results = MagicMock(name="Results", side_effect=lambda path: events.append("results:" + path) or prev)
            operator_cls = MagicMock(name="CoupledOperator", side_effect=lambda *a, **k: events.append("operator") or "OPERATOR")
            integrator_cls = MagicMock(name="PredictorIntegrator")
            stub_deplete.CoupledOperator = operator_cls
            for name in INTEGRATORS:
                setattr(stub_deplete, name, integrator_cls if name == "PredictorIntegrator" else MagicMock(name=name))
            with tempfile.TemporaryDirectory(prefix="studio-depl-") as tmp:
                model_file = Path(tmp) / "model.py"
                model_file.write_text("import builtins\nmodel = 'MODEL'\n"
                                      "def prepare_depletion(m, measure_volumes=True):\n    builtins._depl_events.append(f'prepare:{m}:{measure_volumes}')\n", encoding="utf-8")
                script_file = Path(tmp) / "run.py"
                script_file.write_text(build_script(dict(self.BASE, model_path=str(model_file), write_rates=True, resume=True)), encoding="utf-8")
                with patch.dict(sys.modules, {"openmc": stub_openmc, "openmc.deplete": stub_deplete}):
                    runpy.run_path(str(script_file))
        finally:
            del builtins._depl_events
        self.assertEqual(events, ["prepare:MODEL:False", "results:depletion_results.h5", "volumes:MODEL", "operator"])
        operator_cls.assert_called_once_with("MODEL", chain_file="/path/to/chain.xml", prev_results=prev, reduce_chain_level=3)
        integrator_cls.assert_called_once_with("OPERATOR", [1.0, 4.0, 10.0], power_density=38.0, timestep_units="d", continue_timesteps=True)
        integrator_cls.return_value.integrate.assert_called_once_with(write_rates=True)


if __name__ == "__main__":
    unittest.main(verbosity=2)
