"""
B-10 thick slab — model.py generated by OpenMC Studio

Fixed-source run: 2 cells, 1 source, 1 tally, seed 12345.
Run it inside your OpenMC environment (OpenMC 0.14 or newer):
    python model.py
OPENMC_CROSS_SECTIONS must point at a cross_sections.xml.
"""
import openmc
import numpy as np

# ── Materials ──────────────────────────────────────────────
# Pure B-10 at a low density: an absorber for the analytic SEED oracle cases
mat_boron_10 = openmc.Material(name="Boron-10")
mat_boron_10.set_density("g/cm3", 0.001)
mat_boron_10.add_nuclide("B10", 1.0, "ao")

materials = openmc.Materials([mat_boron_10])

# ── Geometry ───────────────────────────────────────────────
# Every surface is created once and shared, so faces that touch (or sit on the world
# boundary) are one surface and particles are never lost between them.
# Parts listed first win where shapes overlap (same order as the Explorer).
sphere_r60 = openmc.Sphere(r=60.0, boundary_type="vacuum")
world = -sphere_r60

xplane_0 = openmc.XPlane(0.0)
xplane_12 = openmc.XPlane(12.0)
yplane_m20 = openmc.YPlane(-20.0)
yplane_20 = openmc.YPlane(20.0)
zplane_m20 = openmc.ZPlane(-20.0)
zplane_20 = openmc.ZPlane(20.0)
shape_b_10_slab = +xplane_0 & -xplane_12 & +yplane_m20 & -yplane_20 & +zplane_m20 & -zplane_20

cell_b_10_slab = openmc.Cell(name="B-10 slab", fill=mat_boron_10, region=shape_b_10_slab & world)
cell_world = openmc.Cell(name="World", fill=None, region=world & ~(shape_b_10_slab))
geometry = openmc.Geometry([cell_b_10_slab, cell_world])

# ── Sources ────────────────────────────────────────────────
src_source = openmc.IndependentSource()
src_source.particle = "neutron"
src_source.space = openmc.stats.Point((-3.0, 0.0, 0.0))
src_source.angle = openmc.stats.Monodirectional((1.0, 0.0, 0.0))
src_source.energy = openmc.stats.Discrete([0.0253], [1.0])  # eV
src_source.strength = 1.0

# ── Tallies ────────────────────────────────────────────────
tally_b_10_thick_slab = openmc.Tally(name="B-10 thick slab")
tally_b_10_thick_slab.filters = [openmc.CellFilter([cell_b_10_slab])]
tally_b_10_thick_slab.scores = ["absorption", "flux"]

tallies = openmc.Tallies([tally_b_10_thick_slab])

# ── Settings ───────────────────────────────────────────────
settings = openmc.Settings()
settings.run_mode = "fixed source"
settings.particles = 20000
settings.batches = 10
settings.temperature = {'default': 294.0, 'method': "nearest"}
settings.seed = 12345  # same seed + same model = the same particle histories
settings.source = [src_source]
# Fission is treated as capture, so chains die out in this fixed-source run (MCNP: NONU).
settings.create_fission_neutrons = False

# Stable object IDs for MCNP comment links (no effect on transport).
import json as _studio_json
studio_ids = {
    "cell": {cell_b_10_slab.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\"}"), cell_world.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\"}")},
    "material": {mat_boron_10.id: _studio_json.loads("{\"kind\":\"material\",\"id\":\"b10\"}")},
    "tally": {tally_b_10_thick_slab.id: _studio_json.loads("{\"kind\":\"tally\",\"id\":\"tally\"}")},
    "lattice": {},
    "surface": {sphere_r60.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\",\"slot\":0}"), xplane_0.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":1}"), xplane_12.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":2}"), yplane_m20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":3}"), yplane_20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":4}"), zplane_m20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":5}"), zplane_20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":6}")},
    "source": {0: _studio_json.loads("{\"kind\":\"source\",\"id\":\"src\"}")},
}

model = openmc.Model(geometry=geometry, materials=materials, settings=settings, tallies=tallies)

if __name__ == "__main__":
    import sys
    if "--export-xml" in sys.argv:  # OpenMC Studio exports model.xml this way for MCNP translation
        model.export_to_model_xml()
        raise SystemExit(0)
    statepoint = model.run()
    print(f"Finished: {statepoint}")
