"""
B-10 heating profile — model.py generated by OpenMC Studio

Fixed-source run: 2 cells, 1 source, 2 tallies, seed 12345.
Run it inside your OpenMC environment (OpenMC 0.14 or newer):
    python model.py
OPENMC_CROSS_SECTIONS must point at a cross_sections.xml.
"""
import openmc
import numpy as np

# ── Materials ──────────────────────────────────────────────
# Pure B-10 at a low density: an absorber for the analytic SEED oracle cases
mat_boron_10 = openmc.Material(name="Boron-10")
mat_boron_10.set_density("g/cm3", 0.001)
mat_boron_10.add_nuclide("B10", 1.0, "ao")

materials = openmc.Materials([mat_boron_10])

# ── Geometry ───────────────────────────────────────────────
# Every surface is created once and shared, so faces that touch (or sit on the world
# boundary) are one surface and particles are never lost between them.
# Parts listed first win where shapes overlap (same order as the Explorer).
sphere_r60 = openmc.Sphere(r=60.0, boundary_type="vacuum")
world = -sphere_r60

xplane_m20 = openmc.XPlane(-20.0)
xplane_20 = openmc.XPlane(20.0)
yplane_m20 = openmc.YPlane(-20.0)
yplane_20 = openmc.YPlane(20.0)
zplane_0 = openmc.ZPlane(0.0)
zplane_4 = openmc.ZPlane(4.0)
shape_b_10_slab = +xplane_m20 & -xplane_20 & +yplane_m20 & -yplane_20 & +zplane_0 & -zplane_4

cell_b_10_slab = openmc.Cell(name="B-10 slab", fill=mat_boron_10, region=shape_b_10_slab & world)
cell_world = openmc.Cell(name="World", fill=None, region=world & ~(shape_b_10_slab))
geometry = openmc.Geometry([cell_b_10_slab, cell_world])

# ── Sources ────────────────────────────────────────────────
src_source = openmc.IndependentSource()
src_source.particle = "neutron"
src_source.space = openmc.stats.Point((0.0, 0.0, -3.0))
src_source.angle = openmc.stats.Monodirectional((0.0, 0.0, 1.0))
src_source.energy = openmc.stats.Discrete([0.0253], [1.0])  # eV
src_source.strength = 1.0

# ── Tallies ────────────────────────────────────────────────
tally_b_10_profile_slab = openmc.Tally(name="B-10 profile slab")
tally_b_10_profile_slab.filters = [openmc.CellFilter([cell_b_10_slab])]
tally_b_10_profile_slab.scores = ["heating"]

mesh_b_10_profile_mesh = openmc.RegularMesh(name="B-10 profile mesh")
mesh_b_10_profile_mesh.dimension = [1, 1, 4]
mesh_b_10_profile_mesh.lower_left = [-20.0, -20.0, 0.0]
mesh_b_10_profile_mesh.upper_right = [20.0, 20.0, 4.0]
tally_b_10_profile_mesh = openmc.Tally(name="B-10 profile mesh")
tally_b_10_profile_mesh.filters = [openmc.MeshFilter(mesh_b_10_profile_mesh)]
tally_b_10_profile_mesh.scores = ["heating"]

tallies = openmc.Tallies([tally_b_10_profile_slab, tally_b_10_profile_mesh])

# ── Settings ───────────────────────────────────────────────
settings = openmc.Settings()
settings.run_mode = "fixed source"
settings.particles = 20000
settings.batches = 10
settings.temperature = {'default': 294.0, 'method': "nearest"}
settings.seed = 12345  # same seed + same model = the same particle histories
settings.source = [src_source]
# Fission is treated as capture, so chains die out in this fixed-source run (MCNP: NONU).
settings.create_fission_neutrons = False

# Stable object IDs for MCNP comment links (no effect on transport).
import json as _studio_json
studio_ids = {
    "cell": {cell_b_10_slab.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\"}"), cell_world.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\"}")},
    "material": {mat_boron_10.id: _studio_json.loads("{\"kind\":\"material\",\"id\":\"b10\"}")},
    "tally": {tally_b_10_profile_slab.id: _studio_json.loads("{\"kind\":\"tally\",\"id\":\"tally\"}"), tally_b_10_profile_mesh.id: _studio_json.loads("{\"kind\":\"tally\",\"id\":\"mesh\"}")},
    "lattice": {},
    "surface": {sphere_r60.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\",\"slot\":0}"), xplane_m20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":1}"), xplane_20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":2}"), yplane_m20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":3}"), yplane_20.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":4}"), zplane_0.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":5}"), zplane_4.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"slab\",\"slot\":6}")},
    "source": {0: _studio_json.loads("{\"kind\":\"source\",\"id\":\"src\"}")},
}

model = openmc.Model(geometry=geometry, materials=materials, settings=settings, tallies=tallies)

if __name__ == "__main__":
    import sys
    if "--export-xml" in sys.argv:  # OpenMC Studio exports model.xml this way for MCNP translation
        model.export_to_model_xml()
        raise SystemExit(0)
    statepoint = model.run()
    print(f"Finished: {statepoint}")
