"""
Void sphere — model.py generated by OpenMC Studio

Fixed-source run: 2 cells, 1 source, 1 tally, seed 12345.
Run it inside your OpenMC environment (OpenMC 0.14 or newer):
    python model.py
OPENMC_CROSS_SECTIONS must point at a cross_sections.xml.
"""
import openmc
import numpy as np

# ── Materials ──────────────────────────────────────────────
materials = openmc.Materials([])

# ── Geometry ───────────────────────────────────────────────
# Every surface is created once and shared, so faces that touch (or sit on the world
# boundary) are one surface and particles are never lost between them.
# Parts listed first win where shapes overlap (same order as the Explorer).
sphere_r60 = openmc.Sphere(r=60.0, boundary_type="vacuum")
world = -sphere_r60

sphere_r4 = openmc.Sphere(r=4.0)
shape_void_ball = -sphere_r4

cell_void_ball = openmc.Cell(name="Void ball", fill=None, region=shape_void_ball & world)
cell_world = openmc.Cell(name="World", fill=None, region=world & ~(shape_void_ball))
geometry = openmc.Geometry([cell_void_ball, cell_world])

# ── Sources ────────────────────────────────────────────────
src_source = openmc.IndependentSource()
src_source.particle = "neutron"
src_source.space = openmc.stats.Point((0.0, 0.0, 0.0))
src_source.angle = openmc.stats.Isotropic()
src_source.energy = openmc.stats.Discrete([1e6], [1.0])  # eV
src_source.strength = 1.0

# ── Tallies ────────────────────────────────────────────────
tally_void_ball = openmc.Tally(name="Void ball")
tally_void_ball.filters = [openmc.CellFilter([cell_void_ball])]
tally_void_ball.scores = ["flux"]

tallies = openmc.Tallies([tally_void_ball])

# ── Settings ───────────────────────────────────────────────
settings = openmc.Settings()
settings.run_mode = "fixed source"
settings.particles = 20000
settings.batches = 10
settings.temperature = {'default': 294.0, 'method': "nearest"}
settings.seed = 12345  # same seed + same model = the same particle histories
settings.source = [src_source]
# Fission is treated as capture, so chains die out in this fixed-source run (MCNP: NONU).
settings.create_fission_neutrons = False

# Stable object IDs for MCNP comment links (no effect on transport).
import json as _studio_json
studio_ids = {
    "cell": {cell_void_ball.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"ball\"}"), cell_world.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\"}")},
    "material": {},
    "tally": {tally_void_ball.id: _studio_json.loads("{\"kind\":\"tally\",\"id\":\"tally\"}")},
    "lattice": {},
    "surface": {sphere_r60.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\",\"slot\":0}"), sphere_r4.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"ball\",\"slot\":1}")},
    "source": {0: _studio_json.loads("{\"kind\":\"source\",\"id\":\"src\"}")},
}

model = openmc.Model(geometry=geometry, materials=materials, settings=settings, tallies=tallies)

if __name__ == "__main__":
    import sys
    if "--export-xml" in sys.argv:  # OpenMC Studio exports model.xml this way for MCNP translation
        model.export_to_model_xml()
        raise SystemExit(0)
    statepoint = model.run()
    print(f"Finished: {statepoint}")
