"""
TRISO particle - illustrative dimensions — model.py generated by OpenMC Studio

Fixed-source run: 6 cells, 1 source, 1 tally, seed 12345.
Run it inside your OpenMC environment (OpenMC 0.14 or newer):
    python model.py
OPENMC_CROSS_SECTIONS must point at a cross_sections.xml.
"""
import openmc
import numpy as np

# ── Materials ──────────────────────────────────────────────
# Illustrative educational material; see accompanying README
mat_uco_kernel = openmc.Material(name="UCO kernel")
mat_uco_kernel.set_density("g/cm3", 10.5)
mat_uco_kernel.add_element("U", 1.0, "ao")
mat_uco_kernel.add_element("O", 1.5, "ao")
mat_uco_kernel.add_element("C", 0.5, "ao")

# Illustrative educational material; see accompanying README
mat_porous_carbon_buffer = openmc.Material(name="Porous carbon buffer")
mat_porous_carbon_buffer.set_density("g/cm3", 1.0)
mat_porous_carbon_buffer.add_element("C", 1.0, "ao")

# Illustrative educational material; see accompanying README
mat_inner_pyrocarbon_ipyc = openmc.Material(name="Inner pyrocarbon (IPyC)")
mat_inner_pyrocarbon_ipyc.set_density("g/cm3", 1.9)
mat_inner_pyrocarbon_ipyc.add_element("C", 1.0, "ao")

# Illustrative educational material; see accompanying README
mat_silicon_carbide_sic = openmc.Material(name="Silicon carbide (SiC)")
mat_silicon_carbide_sic.set_density("g/cm3", 3.2)
mat_silicon_carbide_sic.add_element("Si", 1.0, "ao")
mat_silicon_carbide_sic.add_element("C", 1.0, "ao")

# Illustrative educational material; see accompanying README
mat_outer_pyrocarbon_opyc = openmc.Material(name="Outer pyrocarbon (OPyC)")
mat_outer_pyrocarbon_opyc.set_density("g/cm3", 1.9)
mat_outer_pyrocarbon_opyc.add_element("C", 1.0, "ao")

materials = openmc.Materials([mat_uco_kernel, mat_porous_carbon_buffer, mat_inner_pyrocarbon_ipyc, mat_silicon_carbide_sic, mat_outer_pyrocarbon_opyc])

# ── Geometry ───────────────────────────────────────────────
# Every surface is created once and shared, so faces that touch (or sit on the world
# boundary) are one surface and particles are never lost between them.
# Parts listed first win where shapes overlap (same order as the Explorer).
sphere_r0p06 = openmc.Sphere(r=0.06, boundary_type="vacuum")
world = -sphere_r0p06

sphere_r0p025 = openmc.Sphere(r=0.025)
shape_uco_kernel = -sphere_r0p025
sphere_r0p035 = openmc.Sphere(r=0.035)
shape_porous_carbon_buffer = -sphere_r0p035
sphere_r0p039 = openmc.Sphere(r=0.039)
shape_inner_pyrocarbon_ipyc = -sphere_r0p039
sphere_r0p0425 = openmc.Sphere(r=0.0425)
shape_silicon_carbide_sic = -sphere_r0p0425
sphere_r0p046 = openmc.Sphere(r=0.046)
shape_outer_pyrocarbon_opyc = -sphere_r0p046

cell_uco_kernel = openmc.Cell(name="UCO kernel", fill=mat_uco_kernel, region=shape_uco_kernel & world)
cell_porous_carbon_buffer = openmc.Cell(name="Porous carbon buffer", fill=mat_porous_carbon_buffer, region=shape_porous_carbon_buffer & world & ~(shape_uco_kernel))
cell_inner_pyrocarbon_ipyc = openmc.Cell(name="Inner pyrocarbon (IPyC)", fill=mat_inner_pyrocarbon_ipyc, region=shape_inner_pyrocarbon_ipyc & world & ~(shape_uco_kernel | shape_porous_carbon_buffer))
cell_silicon_carbide_sic = openmc.Cell(name="Silicon carbide (SiC)", fill=mat_silicon_carbide_sic, region=shape_silicon_carbide_sic & world & ~(shape_uco_kernel | shape_porous_carbon_buffer | shape_inner_pyrocarbon_ipyc))
cell_outer_pyrocarbon_opyc = openmc.Cell(name="Outer pyrocarbon (OPyC)", fill=mat_outer_pyrocarbon_opyc, region=shape_outer_pyrocarbon_opyc & world & ~(shape_uco_kernel | shape_porous_carbon_buffer | shape_inner_pyrocarbon_ipyc | shape_silicon_carbide_sic))
cell_world = openmc.Cell(name="World", fill=None, region=world & ~(shape_uco_kernel | shape_porous_carbon_buffer | shape_inner_pyrocarbon_ipyc | shape_silicon_carbide_sic | shape_outer_pyrocarbon_opyc))
geometry = openmc.Geometry([cell_uco_kernel, cell_porous_carbon_buffer, cell_inner_pyrocarbon_ipyc, cell_silicon_carbide_sic, cell_outer_pyrocarbon_opyc, cell_world])

# ── Sources ────────────────────────────────────────────────
src_illustrative_2_mev_center_source = openmc.IndependentSource()
src_illustrative_2_mev_center_source.particle = "neutron"
src_illustrative_2_mev_center_source.space = openmc.stats.Point((0.0, 0.0, 0.0))
src_illustrative_2_mev_center_source.angle = openmc.stats.Isotropic()
src_illustrative_2_mev_center_source.energy = openmc.stats.Discrete([2e6], [1.0])  # eV
src_illustrative_2_mev_center_source.strength = 1.0

# ── Tallies ────────────────────────────────────────────────
tally_flux_by_particle_layer = openmc.Tally(name="Flux by particle layer")
tally_flux_by_particle_layer.filters = [openmc.CellFilter([cell_uco_kernel, cell_porous_carbon_buffer, cell_inner_pyrocarbon_ipyc, cell_silicon_carbide_sic, cell_outer_pyrocarbon_opyc])]
tally_flux_by_particle_layer.scores = ["flux"]

tallies = openmc.Tallies([tally_flux_by_particle_layer])

# ── Settings ───────────────────────────────────────────────
settings = openmc.Settings()
settings.run_mode = "fixed source"
settings.particles = 1000
settings.batches = 10
settings.temperature = {'default': 293.6, 'method': "interpolation"}
settings.seed = 12345  # same seed + same model = the same particle histories
settings.source = [src_illustrative_2_mev_center_source]
# Fission is treated as capture, so chains die out in this fixed-source run (MCNP: NONU).
settings.create_fission_neutrons = False

# Stable object IDs for MCNP comment links (no effect on transport).
import json as _studio_json
studio_ids = {
    "cell": {cell_uco_kernel.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p0\"}"), cell_porous_carbon_buffer.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p1\"}"), cell_inner_pyrocarbon_ipyc.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p2\"}"), cell_silicon_carbide_sic.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p3\"}"), cell_outer_pyrocarbon_opyc.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p4\"}"), cell_world.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\"}")},
    "material": {mat_uco_kernel.id: _studio_json.loads("{\"kind\":\"material\",\"id\":\"triso_m0\"}"), mat_porous_carbon_buffer.id: _studio_json.loads("{\"kind\":\"material\",\"id\":\"triso_m1\"}"), mat_inner_pyrocarbon_ipyc.id: _studio_json.loads("{\"kind\":\"material\",\"id\":\"triso_m2\"}"), mat_silicon_carbide_sic.id: _studio_json.loads("{\"kind\":\"material\",\"id\":\"triso_m3\"}"), mat_outer_pyrocarbon_opyc.id: _studio_json.loads("{\"kind\":\"material\",\"id\":\"triso_m4\"}")},
    "tally": {tally_flux_by_particle_layer.id: _studio_json.loads("{\"kind\":\"tally\",\"id\":\"triso_flux\"}")},
    "lattice": {},
    "surface": {sphere_r0p06.id: _studio_json.loads("{\"kind\":\"world\",\"id\":\"world\",\"slot\":0}"), sphere_r0p025.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p0\",\"slot\":1}"), sphere_r0p035.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p1\",\"slot\":2}"), sphere_r0p039.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p2\",\"slot\":3}"), sphere_r0p0425.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p3\",\"slot\":4}"), sphere_r0p046.id: _studio_json.loads("{\"kind\":\"part\",\"id\":\"triso_p4\",\"slot\":5}")},
    "source": {0: _studio_json.loads("{\"kind\":\"source\",\"id\":\"triso_source\"}")},
}

model = openmc.Model(geometry=geometry, materials=materials, settings=settings, tallies=tallies)

if __name__ == "__main__":
    import sys
    if "--export-xml" in sys.argv:  # OpenMC Studio exports model.xml this way for MCNP translation
        model.export_to_model_xml()
        raise SystemExit(0)
    statepoint = model.run()
    print(f"Finished: {statepoint}")
