// Generates oracles/seed: the SEED oracle entries of OpenMC Studio, their Studio projects and the model.py each project generates.
//
//   node studio/tools/gen_seed_oracles.cjs [--check]
//
// Needs an Electron binary (SEED_ELECTRON, else a sibling SEED clone's node_modules) to regenerate model.py with Studio's own page, and
// oracles/seed/xs/b10-294K-0.0253eV.json (written once by studio/tools/seed_oracle_xs.py in the OpenMC environment). With --check nothing is
// written: the files on disk must equal what this script generates (exit 1 otherwise).
//
// RULES (fixed before any case was ever run; do not change a number here because a run disagreed):
//  1. An expected value comes from a formula and from the cross sections read out of the nuclear data library. Transport never produces one.
//  2. A tolerance is 4 sigma of the statistical error the formula predicts for the case's number of histories, plus, where the formula neglects
//     something, a bound on what it neglects. It is computed here, from the case alone.
//  3. A case that fails is a finding about the adapter or OpenMC, not a reason to widen a tolerance.
"use strict";
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { spawnSync } = require("child_process");

const ROOT = path.join(__dirname, "..", "..");
const OUT = path.join(ROOT, "oracles", "seed");
const XS = JSON.parse(fs.readFileSync(path.join(OUT, "xs", "b10-294K-0.0253eV.json"), "utf8"));
const EXAMPLE = JSON.parse(fs.readFileSync(path.join(ROOT, "examples", "triso-particle", "triso-particle.openmc-studio.json"), "utf8"));
const check = process.argv.includes("--check");

const sha256 = (data) => crypto.createHash("sha256").update(data).digest("hex");
const sorted = (v) => (Array.isArray(v) ? v.map(sorted) : v && typeof v === "object" ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, sorted(v[k])])) : v);
const canonical = (v) => JSON.stringify(sorted(v));
const dump = (v) => JSON.stringify(sorted(v), null, 1) + "\n";
const round3up = (x) => {
  const m = 10 ** (Math.floor(Math.log10(x)) - 2);
  return Number((Math.ceil(x / m) * m).toPrecision(3));
}; // up to three significant digits

// ---- the physics of the analytic cases -----------------------------------------------------------------------------------------------
const PARTICLES = 20000;
const BATCHES = 10;
const N_HIST = PARTICLES * BATCHES;
const SEED = 12345;
const NEGLECTED_SCATTER = 0.004; // bound on what the first-flight formulas neglect (see the case texts): elastic scattering is 0.057 % of the total cross section

const numberDensity = (rho) => (rho * XS.avogadro_per_mol) / XS.atomic_mass_amu * 1e-24; // atoms per barn-cm
const sigmaA = (rho) => numberDensity(rho) * XS.sigma_absorption_b; // 1/cm
const sigmaT = (rho) => numberDensity(rho) * XS.sigma_total_b;

/** First-flight absorption probability in a slab hit by a beam along its normal, and its binomial statistical error (relative) for N histories. */
function absorption(rho, t) {
  const St = sigmaT(rho);
  const P = (sigmaA(rho) / St) * (1 - Math.exp(-St * t));
  return { value: P, sigmaRel: Math.sqrt((1 - P) / (P * N_HIST)), tau: St * t };
}
/** Track length of the beam in the slab (cm per source particle): E[min(X, t)], X ~ Exp(Sigma_t); its variance gives the statistical error. */
function trackLength(rho, t) {
  const St = sigmaT(rho);
  const tau = St * t;
  const mean = (1 - Math.exp(-tau)) / St;
  const second = (2 / (St * St)) * (1 - Math.exp(-tau) * (1 + tau));
  return { value: mean, sigmaRel: Math.sqrt(Math.max(second - mean * mean, 0) / N_HIST) / mean, tau };
}

// ---- Studio projects -----------------------------------------------------------------------------------------------------------------
const part = (o) => ({ id: "p", name: "part", shape: "box", x: 0, y: 0, z: 0, r: 10, r2: 5, h: 20, a: 15, b: 10, c: 8, axis: "z", sx: 20, sy: 20, sz: 20, rx: 0, ry: 0, rz: 0, material: "void", ...o });
function project(name, { parts, materials = [], source, tally, tallies, settings = {} }) {
  return {
    materials,
    parts,
    groups: [],
    sources: [{ ...EXAMPLE.sources[0], id: "src", name: "source", strength: 1, space: "point", x: 0, y: 0, z: 0, angle: "isotropic", energy: "lines", lines: "1:1", ...source }],
    tallies: tallies ?? (tally ? [{ id: "tally", kind: "cell", ebins: "", ...tally }] : []),
    settings: {
      ...EXAMPLE.settings, name, runMode: "fixed source", particles: PARTICLES, batches: BATCHES, inactive: 0, seed: SEED, maxTracks: 0, track: "", photon: false,
      fissionNeutrons: false, temperatureDefault: 294, temperatureMethod: "nearest", worldShape: "sphere", worldR: 60, worldBC: "vacuum", worldFill: "void", ...settings,
    },
    notes: "Generated by studio/tools/gen_seed_oracles.cjs for the SEED oracle set; see oracles/seed/README.md.",
  };
}

const RHO = 1e-3; // g/cm3 of pure B-10: a dilute absorber, so a few centimetres are a few mean free paths
const slab = (name, t) =>
  project(name, {
    materials: [{ id: "b10", name: "Boron-10", color: "#7a7a7a", density: RHO, frac: "ao", comps: "B10:1", sab: "", ref: "Pure B-10 at a low density: an absorber for the analytic SEED oracle cases" }],
    parts: [part({ id: "slab", name: "B-10 slab", shape: "box", x: t / 2, sx: t, sy: 40, sz: 40, material: "b10" })],
    // a beam of 0.0253 eV neutrons (2.53e-8 MeV) along +x onto the slab's face, from 3 cm in front of it
    source: { x: -3, angle: "mono", u: 1, v: 0, w: 0, lines: "2.53e-8:1" },
    tally: { name, cells: ["slab"], scores: ["absorption", "flux"] },
  });

// The heating oracle: the same dilute B-10 slab, but along z with the beam along +z, so a mesh of PROFILE_NZ bins along z is an axial profile (what a
// transfer into a fuel pin reads). Two tallies in one project: the whole slab's heating (the oracle entry) and the heating in the axial bins (the
// SEED adapter's mesh test compares each bin with the same formula).
const PROFILE_T = 4;
const PROFILE_NZ = 4;
const profile = () =>
  project("B-10 heating profile", {
    materials: [{ id: "b10", name: "Boron-10", color: "#7a7a7a", density: RHO, frac: "ao", comps: "B10:1", sab: "", ref: "Pure B-10 at a low density: an absorber for the analytic SEED oracle cases" }],
    parts: [part({ id: "slab", name: "B-10 slab", shape: "box", x: 0, y: 0, z: PROFILE_T / 2, sx: 40, sy: 40, sz: PROFILE_T, material: "b10" })],
    // a beam of 0.0253 eV neutrons along +z onto the slab's face, from 3 cm in front of it
    source: { x: 0, y: 0, z: -3, angle: "mono", u: 0, v: 0, w: 1, lines: "2.53e-8:1" },
    tallies: [
      { id: "tally", kind: "cell", ebins: "", name: "B-10 profile slab", cells: ["slab"], scores: ["heating"] },
      { id: "mesh", kind: "mesh", ebins: "", name: "B-10 profile mesh", cells: [], scores: ["heating"], nx: 1, ny: 1, nz: PROFILE_NZ, lx: -20, ly: -20, lz: 0, ux: 20, uy: 20, uz: PROFILE_T },
    ],
  });

const voidSphere = (settings = {}, tally = true) =>
  project("Void sphere", {
    parts: [part({ id: "ball", name: "Void ball", shape: "sphere", r: 4, material: "void" })],
    source: {},
    tally: tally ? { name: "Void ball", cells: ["ball"], scores: ["flux"] } : null,
    settings,
  });

const CASES = [];
{
  const r = 4;
  CASES.push({
    id: "void-ball-flux", model: voidSphere(),
    entries: [{ quantity: "Void ball:flux", unit: "cm", value: r, tol: { abs: 0, rel: 1e-9 } }],
    source: { kind: "analytic", text: "A point source at the centre of a void ball of radius 4 cm. Every particle flies along a radius and crosses the whole ball, so the track length in it is exactly 4 cm per source particle, with no statistical error.", check: "Independent of OpenMC's transport and of any cross section: pure geometry." },
    coverage: { quantities: ["Void ball:flux"], domain: "fixed source, void geometry, point isotropic source, cell flux (track length)" },
  });
}
for (const [id, t, label] of [["b10-slab-thin", 4, "thin"], ["b10-slab-thick", 12, "thick"]]) {
  const name = `B-10 ${label} slab`;
  const a = absorption(RHO, t);
  const f = trackLength(RHO, t);
  const text = (what, tau, rel) =>
    `A beam of 0.0253 eV neutrons along +x onto a ${t} cm slab of pure B-10 (${RHO} g/cm3, 294 K), ${PARTICLES} x ${BATCHES} histories, seed ${SEED}. ${what} Optical thickness ${tau.toFixed(3)}. ` +
    `Cross sections (total ${XS.sigma_total_b.toFixed(2)} b, absorption ${XS.sigma_absorption_b.toFixed(2)} b) read from the library file ${XS.library.file} (sha256 ${XS.library.file_sha256.slice(0, 12)}...) by studio/tools/seed_oracle_xs.py. ` +
    `Tolerance: 4 sigma of the predicted statistical error (${(rel * 100).toFixed(3)} % per sigma) plus ${NEGLECTED_SCATTER * 100} % for the neglected elastic scattering (0.057 % of all collisions).`;
  CASES.push({
    id, model: slab(name, t),
    entries: [
      { quantity: `${name}:absorption`, unit: "reaction", value: a.value, tol: { abs: 0, rel: round3up(4 * a.sigmaRel + NEGLECTED_SCATTER) }, key: "absorption",
        text: text("Expected: the first-flight absorption probability (Sigma_a/Sigma_t)(1 - exp(-Sigma_t t)).", a.tau, a.sigmaRel) },
      { quantity: `${name}:flux`, unit: "cm", value: f.value, tol: { abs: 0, rel: round3up(4 * f.sigmaRel + NEGLECTED_SCATTER) }, key: "flux",
        text: text("Expected: the beam's track length in the slab, (1 - exp(-Sigma_t t))/Sigma_t, which is also absorption / Sigma_a.", f.tau, f.sigmaRel) },
    ],
    source: { kind: "analytic", check: "Independent of OpenMC's transport: the formula and the library cross sections only. The absorption and flux entries are tied by absorption = Sigma_a x flux." },
    coverage: { quantities: [`${name}:absorption`, `${name}:flux`], domain: "fixed source, 0.0253 eV beam on a pure B-10 slab (optical thickness 0.9 to 2.8), 294 K" },
  });
}

{
  // Heating: the flux tally weighted with the library's neutron heating (KERMA) cross section at 0.0253 eV, N_B10 * kappa * track length. The
  // heating cross section is read from the library (MT 301, eV-barn) with the others, never from a transport run.
  const f = trackLength(RHO, PROFILE_T);
  const name = "B-10 profile slab";
  const kappa = XS.heating_eV_b;
  const value = numberDensity(RHO) * kappa * f.value;
  const text =
    `A beam of 0.0253 eV neutrons along +z onto a ${PROFILE_T} cm slab of pure B-10 (${RHO} g/cm3, 294 K), ${PARTICLES} x ${BATCHES} histories, seed ${SEED}, neutrons only. ` +
    `Expected: the heating per source particle in the slab, N kappa (1 - exp(-Sigma_t t))/Sigma_t, with kappa = ${kappa.toPrecision(10)} eV b the library's neutron heating cross section ` +
    `at 0.0253 eV (MT 301 of ${XS.library.file}, sha256 ${XS.library.file_sha256.slice(0, 12)}...) and the beam's track length from the flux formula (optical thickness ${f.tau.toFixed(3)}). ` +
    `Heating per absorption is kappa / sigma_a = ${(kappa / XS.sigma_absorption_b / 1e6).toFixed(3)} MeV. ` +
    `Tolerance: 4 sigma of the predicted statistical error (${(f.sigmaRel * 100).toFixed(3)} % per sigma, the track-length variance) plus ${NEGLECTED_SCATTER * 100} % for the neglected elastic scattering.`;
  CASES.push({
    id: "b10-heating-profile", model: profile(),
    entries: [{ quantity: `${name}:heating`, unit: "eV", value, key: "heating", tol: { abs: 0, rel: round3up(4 * f.sigmaRel + NEGLECTED_SCATTER) }, text }],
    source: {
      kind: "analytic",
      check: `Independent of OpenMC's transport: the formula and the library cross sections only. The same project also holds a ${PROFILE_NZ}-bin axial mesh tally of heating, which the SEED adapter's tests compare with the formula per bin (the entry itself judges the whole slab).`,
    },
    coverage: { quantities: [`${name}:heating`], domain: "fixed source, 0.0253 eV beam on a 4 cm pure B-10 slab (optical thickness 0.9), 294 K, neutron heating (no photon transport)" },
  });
}

const BAD = [
  ["bad-eigenvalue", voidSphere({ runMode: "eigenvalue" }), "E_UNSUPPORTED", "An eigenvalue project. The first slice runs fixed-source cases only, so the runner must refuse it before anything is reserved."],
  ["bad-too-many-particles", voidSphere({ particles: 2000000 }), "E_BOUNDS_EXCEEDED", "Two million particles per batch: over the runner's limit of one million. It must be refused as out of bounds."],
  ["bad-no-tally", voidSphere({}, false), "E_SCHEMA_INVALID", "A project with no tally: a run would produce no result, so the runner refuses it."],
];

// ---- writing -------------------------------------------------------------------------------------------------------------------------
const electron = [process.env.SEED_ELECTRON, path.join(ROOT, "..", "seed-gate", "node_modules", "electron", "dist", process.platform === "win32" ? "electron.exe" : "electron")].find((p) => p && fs.existsSync(p));
if (!electron) {
  console.error("no Electron binary: set SEED_ELECTRON");
  process.exit(2);
}
function regenerate(projectFile, outFile) {
  const env = { ...process.env };
  delete env.ELECTRON_RUN_AS_NODE;
  const r = spawnSync(electron, [path.join(__dirname, "regen_script.cjs"), projectFile, outFile], { encoding: "utf8", env });
  if (r.status !== 0) throw new Error("regen_script failed for " + projectFile + ": " + r.stdout + r.stderr);
}

const files = new Map(); // relative path -> text
const tmp = fs.mkdtempSync(path.join(require("os").tmpdir(), "openmc-oracles-"));
try {
  const entryOf = (o) => ({ schema: "seed.oracle/0.1", entryVersion: 1, adapter: "openmc", adapterVersions: ["*"], ...o });
  const withHash = (e) => ({ ...e, toleranceHash: sha256(canonical({ expected: e.expected ?? null, tolerance: e.tolerance ?? null })) });
  for (const c of CASES) {
    const projectRel = `models/${c.id}.openmc-studio.json`;
    const scriptRel = `models/${c.id}.py`;
    const projectText = dump(c.model);
    files.set(projectRel, projectText);
    const pf = path.join(tmp, c.id + ".json");
    const sf = path.join(tmp, c.id + ".py");
    fs.writeFileSync(pf, projectText);
    regenerate(pf, sf);
    const scriptText = fs.readFileSync(sf, "utf8");
    files.set(scriptRel, scriptText);
    const inputs = [{ path: projectRel, sha256: sha256(projectText) }, { path: scriptRel, sha256: sha256(scriptText) }];
    for (const e of c.entries) {
      const id = e.key ? `openmc-${c.id}-${e.key}` : `openmc-${c.id}`;
      files.set(`entries/${id}.json`, dump(withHash(entryOf({
        oracleId: id, tag: "good", inputs,
        expected: { quantity: e.quantity, unit: e.unit, value: e.value }, tolerance: e.tol,
        source: { kind: c.source.kind, text: e.text || c.source.text, check: c.source.check }, coverage: c.coverage,
      }))));
    }
  }
  for (const [id, model, code, text] of BAD) {
    const projectRel = `models/${id}.openmc-studio.json`;
    const projectText = dump(model);
    files.set(projectRel, projectText);
    files.set(`entries/openmc-${id}.json`, dump(withHash(entryOf({
      oracleId: `openmc-${id}`, tag: "bad-input", inputs: [{ path: projectRel, sha256: sha256(projectText) }],
      expected: { refusalCode: code }, source: { kind: "hand", text, check: "The runner's own first-slice checks (studio/openmc_studio/headless.py, test/test_headless.py) refuse the same faults." },
      coverage: { quantities: ["model-validation"], domain: "project validation and first-slice capability gate" },
    }))));
  }
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}

let differs = 0;
for (const [rel, text] of files) {
  const file = path.join(OUT, rel);
  if (check) {
    const have = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    if (have !== text) {
      differs++;
      console.log("DIFFERS: " + rel);
    }
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text, "utf8");
  }
}
console.log((check ? "checked " : "wrote ") + files.size + " files; " + CASES.reduce((n, c) => n + c.entries.length, 0) + " good entries, " + BAD.length + " bad-input entries");
for (const c of CASES) for (const e of c.entries) console.log("  " + e.quantity.padEnd(34) + " expected " + String(e.value).padEnd(22) + " tolerance rel " + e.tol.rel);
process.exit(differs ? 1 : 0);
