"""Long-running MCNP export worker for OpenMC Studio's live model.mcnp tab.

Starting MCNPy's Java bridge takes a few seconds, so the server keeps one worker
process alive and sends it one job per line on stdin:

    {"id": 7, "folder": "/abs/path", "name": "shielding-demo", "samples": 20000}

The folder must contain model.py (generated by Studio). The worker builds the model
by running model.py without its __main__ block, exports model.xml, then runs the
same three stages as openmc-mcnp-project's export_mcnp.export():
translate (MCNPy) -> remediate_deck.remediate -> validate_deck.validate_deck.

MCNPy translation is slow (~8 s: thousands of Java round trips) and depends only on
geometry and materials, so its output is cached by a hash of those two XML sections.
Edits to sources, tallies or settings re-use the cached translation and finish in
about a second. Each result is one stdout line starting with "@@RESULT "; anything
else on stdout (the JVM's own messages) is ignored by the server.

    python -m openmc_studio.mcnp_worker /path/to/openmc-mcnp-project
"""
import contextlib
import hashlib
import io
import json
import os
import runpy
import shutil
import sys
import tempfile
import time
import xml.etree.ElementTree as ET

_real_stdout = sys.stdout


def emit(obj):
    _real_stdout.write("@@RESULT " + json.dumps(obj) + "\n")
    _real_stdout.flush()


def emit_progress(job_id, step, total, stage, text, t0):
    elapsed = round(time.time() - t0, 1) if t0 else 0
    _real_stdout.write("@@PROGRESS " + json.dumps({
        "id": job_id, "step": step, "total": total, "stage": stage, "text": text, "elapsed": elapsed
    }) + "\n")
    _real_stdout.flush()


class StageForwarder(io.TextIOBase):
    def __init__(self, job_id, t0):
        self.job_id = job_id
        self.t0 = t0
        self.buf = ""

    def write(self, s):
        self.buf += s
        while "\n" in self.buf:
            line, self.buf = self.buf.split("\n", 1)
            self._handle_line(line.strip())
        return len(s)

    def _handle_line(self, line):
        if not line:
            return
        stage_map = [
            ("Translating Materials", (2, "materials", "Translating materials...")),
            ("Translating Surfaces", (3, "surfaces", "Translating surfaces...")),
            ("Translating Universes and Cells", (4, "cells", "Translating universes and cells...")),
            ("Making Universes", (4, "cells", "Making universes...")),
            ("Filling Cells", (5, "cells", "Filling cells...")),
            ("Constructing Lattices", (6, "lattices", "Constructing lattices...")),
        ]
        for trigger, (step, stage, text) in stage_map:
            if trigger in line:
                emit_progress(self.job_id, step, 8, stage, text, self.t0)
                break

    def flush(self):
        if self.buf.strip():
            self._handle_line(self.buf.strip())
            self.buf = "" 


def geometry_key(model_xml):
    root = ET.parse(model_xml).getroot()
    h = hashlib.sha256()
    for tag in ("materials", "geometry"):
        el = root.find(tag)
        h.update(ET.tostring(el) if el is not None else b"")
    return h.hexdigest()


ASCII_SUBS = {"×": "x", "°": " deg", "µ": "u", "μ": "u", "–": "-", "—": "-", "−": "-", "²": "2", "³": "3"}


def ascii_label(text):
    """MCNP input is ASCII: common symbols become their plain spelling, anything else '?'; '=' would read as a card."""
    text = "".join(ASCII_SUBS.get(ch, ch) for ch in str(text))
    return text.encode("ascii", "replace").decode("ascii").replace("=", "-")


def collect_group_cards(groups_dict, prefix=""):
    cards = []
    for name, data in groups_dict.items():
        path = f"{prefix}/{name}" if prefix else str(name)
        label = ascii_label(path)
        if isinstance(data, dict):
            pivot = data.get("pivot")
            cells = data.get("cells", [])
            child_groups = data.get("groups", {})
        elif isinstance(data, list):
            pivot = None
            cells = data
            child_groups = {}
        else:
            continue
        
        ids = [str(c.id) for c in (cells or []) if hasattr(c, "id")]
        pivot_str = f" | pivot: {' '.join(str(round(v, 6)) for v in pivot)}" if pivot and len(pivot) == 3 else ""
        
        line = f"c Group: {label}{pivot_str}{' = cells' if ids else ''}"
        for i in ids:  # MCNP input lines stay within 80 columns
            if len(line) + 1 + len(i) > 80:
                cards.append(line)
                line = "c     " + i
            else:
                line += " " + i
        cards.append(line)
        
        if child_groups and isinstance(child_groups, dict):
            cards.extend(collect_group_cards(child_groups, path))
    return cards


def add_group_comments(deck_path, groups):
    """Studio groups (model.py's `groups = {name: [cells]}` or nested dicts) as comment cards right after the title card:
    c Group: Core/Assembly 1 | pivot: x y z = cells 2 3 4. They name cells for the reader and change nothing in the problem."""
    if not isinstance(groups, dict) or not groups:
        return
    cards = collect_group_cards(groups)
    if not cards:
        return
    from deck_format import format_deck
    with open(deck_path) as f:
        lines = f.read().split("\n")
    with open(deck_path, "w") as f:
        f.write(format_deck("\n".join(lines[:1] + cards + lines[1:])))


def main():
    project = os.path.abspath(os.path.expanduser(sys.argv[1]))
    sys.path.insert(0, os.path.join(project, "src"))
    cache_dir = tempfile.mkdtemp(prefix="studio_mcnpy_cache_")
    cache = {}  # geometry key -> cached translated deck path (small, bounded below)
    t0 = time.time()
    try:
        with contextlib.redirect_stdout(io.StringIO()):
            import openmc
            from export_mcnp import translate
            import lattice_cards
            from mcnp_cards import UnsupportedFeature
            from remediate_deck import load_model, remediate
            from validate_deck import validate_deck
            from mcnpy.translate_mcnp_openmc import openmc_to_mcnp  # noqa: F401  (starts the Java bridge once)
    except Exception as e:
        emit({"ready": False, "error": f"Couldn't load the MCNP pipeline from {project}: {type(e).__name__}: {e}"})
        return 1
    emit({"ready": True, "seconds": round(time.time() - t0, 2)})

    try:
        for line in sys.stdin:
            line = line.strip()
            if not line:
                continue
            job = json.loads(line)
            t0 = time.time()
            report = {}
            try:
                folder, name = job["folder"], job["name"]
                os.chdir(folder)
                model_xml = os.path.join(folder, "model.xml")
                translated = os.path.join(folder, f"{name}.mcnp")
                runnable = os.path.join(folder, f"{name}_runnable.mcnp")
                for stale in (model_xml, translated, runnable):
                    if os.path.exists(stale):
                        os.remove(stale)

                emit_progress(job.get("id"), 1, 8, "prepare", "Preparing OpenMC model...", t0)
                openmc.reset_auto_ids()  # IDs start at 1, as in a fresh `python model.py`
                with contextlib.redirect_stdout(io.StringIO()):
                    ns = runpy.run_path(os.path.join(folder, "model.py"), run_name="studio_export")
                    ns["model"].export_to_model_xml(model_xml)
                model = load_model(model_xml)
                report = {"ok": False, "model": model_xml, "translated": translated, "runnable": runnable}

                key = geometry_key(model_xml)
                # same model changes as translate() makes, also when the translation comes from the cache
                prep_notes = lattice_cards.prepare(model)
                report["translation_cached"] = key in cache
                if key in cache:
                    emit_progress(job.get("id"), 6, 8, "cached", "Reusing cached translation...", t0)
                    shutil.copyfile(cache[key], translated)
                else:
                    report["stage"] = "translate"
                    forwarder = StageForwarder(job.get("id"), t0)
                    translate(model, translated, stdout=forwarder)
                    forwarder.flush()
                    if len(cache) >= 20:
                        cache.clear()
                    cached = os.path.join(cache_dir, f"{key}.mcnp")
                    shutil.copyfile(translated, cached)
                    cache[key] = cached

                report["stage"] = "remediate"
                emit_progress(job.get("id"), 7, 8, "remediate", "Remediating deck (sources, tallies, settings)...", t0)
                report.update(remediate(translated, model, runnable, detector_responses=ns.get("detector_responses")))
                report["notes"] = prep_notes + report.get("notes", [])
                add_group_comments(runnable, ns.get("groups"))

                report["stage"] = "validate"
                emit_progress(job.get("id"), 8, 8, "validate", "Validating deck...", t0)
                buf = io.StringIO()
                with contextlib.redirect_stdout(buf):
                    ok = validate_deck(runnable, model=model, geometry_samples=int(job.get("samples", 20000)))
                report["validation"] = buf.getvalue()
                report["ok"] = bool(ok)
                report["stage"] = "done"
                report["deck"] = open(runnable).read()
            except UnsupportedFeature as e:
                report = {"ok": False, "stage": "remediate", "error": f"Not exportable: {e}"}
            except Exception as e:
                report = {"ok": False, "stage": report.get("stage", "error"), "error": f"{type(e).__name__}: {e}"}
            report["id"] = job.get("id")
            report["seconds"] = round(time.time() - t0, 2)
            emit(report)
    finally:
        shutil.rmtree(cache_dir, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
